name: Sending BOI interest report

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 15 * *'

jobs:
  send-report:
    name: 'Sending BOI interest report'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.11']
    env:
      SMTP_SERVER_PASSWORD: ${{ secrets.SMTP_SERVER_PASSWORD }}
      SMTP_SERVER_USER: ${{ secrets.SMTP_SERVER_USER }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          cache-dependency-path: requirements.txt
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip --quiet install -r requirements.txt
      - name: Send stocks report
        run: |
          python boi_interest.py